### ISSUE TITLE
Youtube data collection is not working

### ISSUE THREAD

**Issue by scooter7** [vosonlab/VOSONDash#12]
After inputting a Youtube video URL in multiple formats (as instructed within the app), I got message: 
Total comments collected for all videos 0.
Elapsed time: 0 hrs 0 mins 0 secs (0.47)
youtube collection error: Error in Collect.youtube(credential = structure(list(socialmedia = "youtube", : No comments could be collected from the given video Ids: 6_W0EZXr8AE

**Comment by rjackland** [comment]
Hello - I haven't had any problems with YouTube collection in the past month, so my only thought is that there is a problem with the way the API access has been setup. The following are instructions on this page: http://vosonlab.net/SocialMediaLab/access_API

To access the YouTube API, you need to have a Google account.  When logged into Google, then go to the Google APIs Console and create a project (if you already don't have one).  Then go to the navigation menu (top LHS) APIs&Services->Enable APIs and Services select and enable YouTube Data API version 3.  This API should then appear in the Enabled APIs tab.  Then go to APIs and Services->Credentials and generate a Public API access key.  The API key then needs to be supplied to VOSON Dashboard or vosonSML

**Comment by scooter7** [comment]
Hi, You nailed it! I was using an outdated API key. Everything is working perfectly now. Thanks so much and oustanding work on this Shiny App!

**Comment by rjackland** [comment]
OK good to hear! Thanks for positive feedback on VOSON Dashboard, and please spread the word!
