### ISSUE TITLE
Available for API 2?

### ISSUE THREAD

**Issue by marybetholiver** [vosonlab/VOSONDash#31]
This is such a wonderful package. I'm wondering if there's any way to use the new academic twitter API with it? It doesn't seem to recognize my tokens, but it looks wonderful. Thank you!

**Comment by bryn-g** [comment]
Hi Mary,

We don't currently have support for Twitter API v2 (that the Academic Research track uses) in `vosonSML` or `VOSONDash` but will hopefully be adding that in the coming weeks. We do currently have a package [voson.tcn](https://github.com/vosonlab/voson.tcn) that is for collecting Twitter threaded conversations and creating networks in R, which uses API v2, and that will be added to `VOSONDash` soon. We are also considering adding a `VOSONDash` interface to the [academictwitteR](https://github.com/cjbarrie/academictwitteR) package in the near future and that sounds like it would meet your needs, but unfortunately I can't give you a date at this stage.

Thanks very much for the kind and positive feedback, sorry I couldn't help more but we'll keep you posted.

**Comment by marybetholiver** [comment]
Hi There,

Thank you so much for the kind and helpful reply. I really look forward to
those packages! Such awesome work that you're doing!!

Yours,

Mary

**Comment by bryn-g** [comment]
Closing due to changed circumstances in regard to academic access to the twitter API.
