### ISSUE TITLE
Can't add Reddit URLs on Collection

### ISSUE THREAD

**Issue by Sihtam7292** [vosonlab/VOSONDash#35]
Hi,

First I'd like to thank you for all the hard work you've put into all of this. It is truly impressive, and helps me a lot for Uni projects.

I have an issue with Reddit data collection through VOSON Dashboard. When putting a valid URL into the "Add Reddit URL" frame and selecting "Add", nothing happens and the URL disappears. Even after checking that I've installed and loaded every needed package.

I've only managed to make it work with 1 or 0 answers threads, which doesn't answer what I have to do.
What could cause this ?

Thanks,
Cheers

**Comment by bryn-g** [comment]
Hi there,

Thanks for your message and kind words about the package, we're glad to hear it has been useful in your projects! The problem you describe sounds like an issue validating the URL and I was wondering if I could check with you what version of `vosonSML` and `VOSONDash` you are using?

If you are not using them already, I would recommend installing the github package versions as they have the latest bug fixes and are updated more frequently than the CRAN versions.

```R
# install github versions
if (!require("remotes")) install.packages("remotes")
remotes::install_github("vosonlab/vosonSML")
remotes::install_github("vosonlab/VOSONDash")

# latest github versions
packageVersion("vosonSML")
# [1] ‘0.33.2’
packageVersion("VOSONDash")
# [1] ‘0.6.1’
```

The behaviour you describe with `VOSONDash` occurs when it does not think the `Reddit` URL is valid for a comment thread. Older package versions required a thread ID of 6 characters, which is not always the case, and I suspect that this is what is making it invalid here, or it is missing a trailing forward slash.

You can also manually check a URL as follows:

```R
library(VOSONDash)

# valid
print(createRedditRequestUrl(
 "https://www.reddit.com/r/AustralianPolitics/comments/12hd24r/media_companies_slam_proposed_reforms_to/"
))
# [1] "r/AustralianPolitics/comments/12hd24r/media_companies_slam_proposed_reforms_to/"

# invalid 
print(createRedditRequestUrl(
"https://www.reddit.com/r/AustralianPolitics/comments/12hd24r/media_companies_slam_proposed_reforms_to"
))
# NULL
```

Hope that helps, please let me know if you're still having a problem.

**Comment by Sihtam7292** [comment]
Hi !
Thank you a lot for your help, it works now.

I guess there were some kind of issues with the package version, I used the previous one for VOSONDash.

Have a nice day,
Cheers
